### ISSUE TITLE
can't find install.bat

### ISSUE THREAD

**Issue by pentor11** [cardid/WebCard#6]
I can't find install.bat in step 2 on Installing.

**Comment by adricasti** [comment]
Hi @pentor11, you don't need any bat file to install in Windows, just run the [installer package](https://github.com/cardid/webcard/releases/download/v0.2.3/webcard.msi) or build it yourself from the sources if you prefer.  Installation of the extension is a two step process, taken care by the installer:
1. Copy the native executable and register it so Chrome knows where to find it
2. Add the Chrome extension itself from the Chrome Store
