### ISSUE TITLE
How to Get Serial Number

### ISSUE THREAD

**Issue by teknosains** [cardid/WebCard#9]
Thanks for the extension. I'm able to install it and read a card from a Omnikey reader, like below

![image](https://user-images.githubusercontent.com/3906229/220261612-5e8249ec-1490-4e33-96c1-4e60eb9f3f9c.png)

I wonder how to read the Tag ID / Serial number of the Card?

the serial number of the card is something like this

```
EF:4F:08:CA
```

Thank you @adricasti

**Comment by adricasti** [comment]
Hi @teknosains , just try sending to the card `FFCA000000`, you will get the 4 or 7 byte UID for your card, followed by status 9000

**Comment by teknosains** [comment]
Hi @adricasti thanks it worked...im new to this, how can i find the list of the apdu command like a complete commands for common purpose...

- retrieve serial number (FFCA000000)
- retrieve card number 
- etc

🙏

**Comment by adricasti** [comment]
That really depends on the type of card you are using. Most smart cards would have keys protecting access and you would have to talk to the issuer of the card to have those keys. Maybe some of the scripts from a project like [CardPeek](https://github.com/L1L1/cardpeek/tree/master/dot_cardpeek_dir/scripts) could be a good starting point

**Comment by teknosains** [comment]
Hi @adricasti, Thank  you for the info.
